version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    image: message-blaster:latest
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      # - valkey
    environment:
      - DJANGO_SETTINGS_MODULE=message_blaster.settings

volumes:
  pgdata: